#############################################################################
# Generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#  Dec 27, 2020 11:17:24 PM +03  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top48 {base} {
    global vTcl
    if {$base == ""} {
        set base .top48
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+660+210
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Rent Bike" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    label $top.lab50 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {CodeName: } 
    vTcl:DefineAlias "$top.lab50" "Label1" vTcl:WidgetProc "Rent Bike" 1
    entry $top.ent51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 254 
    vTcl:DefineAlias "$top.ent51" "codename" vTcl:WidgetProc "Rent Bike" 1
    label $top.lab52 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Number of Bikes: } 
    vTcl:DefineAlias "$top.lab52" "Label2" vTcl:WidgetProc "Rent Bike" 1
    entry $top.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 54 
    vTcl:DefineAlias "$top.ent53" "price" vTcl:WidgetProc "Rent Bike" 1
    label $top.lab54 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Select Your Service:} 
    vTcl:DefineAlias "$top.lab54" "Label3" vTcl:WidgetProc "Rent Bike" 1
    radiobutton $top.rad55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {hourly    @5$} -variable hour 
    vTcl:DefineAlias "$top.rad55" "Radiobutton1" vTcl:WidgetProc "Rent Bike" 1
    radiobutton $top.rad56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Daily    @20$} -variable day 
    vTcl:DefineAlias "$top.rad56" "Radiobutton2" vTcl:WidgetProc "Rent Bike" 1
    radiobutton $top.rad57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Weekly   @60$} -variable week 
    vTcl:DefineAlias "$top.rad57" "Radiobutton3" vTcl:WidgetProc "Rent Bike" 1
    button $top.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Confirm 
    vTcl:DefineAlias "$top.but58" "Button1" vTcl:WidgetProc "Rent Bike" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab50 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.156 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.156 -width 254 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.311 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.311 -width 54 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.489 -width 0 -relwidth 0.173 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.rad55 \
        -in $top -x 0 -relx 0.217 -y 0 -rely 0.489 -width 0 -relwidth 0.197 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad56 \
        -in $top -x 0 -relx 0.217 -y 0 -rely 0.556 -width 0 -relwidth 0.197 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad57 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.622 -width 0 -relwidth 0.247 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.844 -width 147 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top48 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

